FROM php:7.2-fpm-alpine

LABEL "com.example.vendor"="etable.gr"
LABEL maintainer="Desyllas Dimitrios <d.desyllas@e-table.gr> <pcmagas@disroot.org>"


RUN apk add --update libzip-dev libmcrypt-dev libpng-dev libjpeg-turbo-dev libxml2-dev icu-dev postgresql-dev curl-dev libmemcached-dev &&\
    apk add --update --virtual build-dependencies build-base gcc wget autoconf &&\    
    docker-php-ext-install bcmath &&\
	docker-php-ext-install opcache && \
 	docker-php-ext-install pdo pdo_pgsql pgsql && \
    docker-php-ext-install sockets &&\
	docker-php-ext-install intl && \
	docker-php-ext-install gd && \
 	docker-php-ext-install soap && \
    docker-php-ext-install curl && \
	docker-php-ext-install mbstring && \
    docker-php-ext-install intl &&\
    docker-php-ext-install pcntl &&\
    pecl install redis &&\
    docker-php-ext-enable redis &&\
    pecl install memcached &&\
    docker-php-ext-enable memcached &&\
    apk del build-dependencies &&\
    rm -rf /var/cache/apk/*

CMD ["php", "-r", "exit();"]