FROM php:7.2-fpm-alpine

LABEL "com.example.vendor"="etable.gr"
LABEL maintainer="Desyllas Dimitrios <d.desyllas@e-table.gr> <pcmagas@disroot.org>"

ENV PHP_CONF_DIR="/usr/local/etc/php/conf.d" \
    FPM_CONF_DIR="/usr/local/etc/php-fpm.d" \
    PHP_SETTINGS="$PHP_INI_DIR/php.ini"\
    SESSION_STORAGE_TYPE="memcache"\
    SESSION_STORAGE_PATH="tcp:\/\/memcache:11211"

RUN apk add --update libzip-dev libmcrypt-dev libpng-dev libjpeg-turbo-dev libxml2-dev icu-dev postgresql-dev curl-dev libmemcached-dev &&\
    apk add --update --virtual build-dependencies build-base gcc wget autoconf &&\    
    docker-php-ext-install bcmath &&\
	docker-php-ext-install opcache && \
 	docker-php-ext-install pdo pdo_pgsql pgsql && \
    docker-php-ext-install sockets &&\
	docker-php-ext-install intl && \
	docker-php-ext-install gd && \
 	docker-php-ext-install soap && \
    docker-php-ext-install curl && \
	docker-php-ext-install mbstring && \
    docker-php-ext-install intl &&\
    docker-php-ext-install pcntl &&\
    pecl install redis &&\
    docker-php-ext-enable redis &&\
    pecl install memcached &&\
    docker-php-ext-enable memcached &&\
    apk del build-dependencies &&\
    echo "Configuring php" &&\
    touch ${PHP_SETTINGS} &&\
    rm -rf /var/cache/apk/*

# For faster Re-Builds

RUN mv "$PHP_INI_DIR/php.ini-production" ${PHP_SETTINGS} &&\
    sed -i "s/max_execution_time = .*/max_execution_time = 45/" ${PHP_SETTINGS} &&\
    sed -i "s/upload_max_filesize = .*/upload_max_filesize = 20M/" ${PHP_SETTINGS} &&\
    sed -i "s/post_max_size = .*/post_max_size = 64M/" ${PHP_SETTINGS} &&\
    sed -i "s/error_reporting = .*/error_reporting = E_ALL \& E_DEPRECATED /" ${PHP_SETTINGS} &&\
    sed -i "s/display_errors = .*/display_errors = On/" ${PHP_SETTINGS} &&\
    sed -i "s/cgi.fix_pathinfo = .*/cgi.fix_pathinfo = 1/" ${PHP_SETTINGS} &&\
    sed -i "s/allow_url_include = .*/allow_url_include = On/" ${PHP_SETTINGS} &&\
    sed -i "s/expose_php = .*/expose_php = Off/" ${PHP_SETTINGS} &&\
    sed -i "s/;date.timezone =/date.timezone = \"Europe\/Athens\"/" ${PHP_SETTINGS} &&\
    sed -i "s/session.save_handler = .*/session.save_handler = ${SESSION_STORAGE_TYPE}/" ${PHP_SETTINGS} &&\
    sed -i "s/;session.save_path = .*/session.save_path = \"${SESSION_STORAGE_PATH}\"/" ${PHP_SETTINGS}

CMD ["php", "-r", "exit();"]