FROM etable/php:base

LABEL "com.example.vendor"="etable.gr"
LABEL maintainer="Desyllas Dimitrios <d.desyllas@e-table.gr> <pcmagas@disroot.org>"

ARG USERID=1000
ARG GROUPID=1000

ENV DOCKER_UID=${USERID} \
    DOCKER_GID=${GROUPID} \
    PHP_CONF_DIR="/usr/local/etc/php/conf.d" \
    XDEBUG_CONF_FILE=${PHP_CONF_DIR}/docker-php-ext-xdebug.ini \
    XDEBUG_HOST="" \
    XDEBUG_IDE_KEY="" \
    XDEBUG_PORT=9000 \
    XDEBUG_DBGP=FALSE


RUN echo "Installing Development Dpendencies \n" &&\
    echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories &&\
    apk add --update --virtual build-dependencies build-base gcc wget autoconf &&\
    apk add --update bash shadow git bash-completion bash-doc &&\
    echo "Installing composer \n" &&\
    php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');" &&\
    php -r "if (hash_file('sha384', '/tmp/composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&\
    php /tmp/composer-setup.php --install-dir=/bin --filename=composer &&\
    rm -rf /tmp/cpmposer-setup.php &&\
    chmod +x /bin/composer &&\
    echo "Installing xdebug" &&\
    pecl install xdebug  &&\
    docker-php-ext-enable xdebug &&\
    echo "Configuring Xdebug \n" &&\
    echo "xdebug.remote_enable=1" >> ${XDEBUG_CONF_FILE} &&\
    echo "xdebug.max_nesting_level = 1000" >> ${XDEBUG_CONF_FILE} &&\
    echo "xdebug.remote_mode=req" >> ${XDEBUG_CONF_FILE} &&\
    echo "xdebug.remote_log=xdebug.log" >> ${XDEBUG_CONF_FILE} &&\
    cp ${XDEBUG_CONF_FILE} ${XDEBUG_CONF_FILE}.orig &&\
    echo "Making a Development User \n" &&\
    addgroup -g ${DOCKER_GID} developer &&\
    mkdir -p /home/developer/code &&\
    adduser -D -u ${DOCKER_UID} -G developer -h /home/developer -s /bin/bash developer &&\
    chown developer:developer -R /home/developer/code &&\
    apk del build-dependencies &&\
    rm -rf /var/cache/apk/*

# I make seperate layer because Entrypoint is most likely to change
COPY ./entrypoint/develop_entrypoint.sh /usr/local/bin/entrypoint.sh

RUN echo "Fixing Permissions on Entrypoint Script \n" &&\
    chown root:root /usr/local/bin/entrypoint.sh &&\
    chmod +x /usr/local/bin/entrypoint.sh

VOLUME /home/developer/code
WORKDIR /home/developer/code

CMD ["/bin/sh","-c","/usr/local/bin/entrypoint.sh"]
